CREATE TABLE  `asteriskcdrdb`.`cdr` (
  `calldate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `clid` varchar(80) NOT NULL DEFAULT '',
  `src` varchar(80) NOT NULL DEFAULT '',
  `dst` varchar(80) NOT NULL DEFAULT '',
  `dcontext` varchar(80) NOT NULL DEFAULT '',
  `channel` varchar(80) NOT NULL DEFAULT '',
  `dstchannel` varchar(80) NOT NULL DEFAULT '',
  `lastapp` varchar(80) NOT NULL DEFAULT '',
  `lastdata` varchar(80) NOT NULL DEFAULT '',
  `duration` int(11) NOT NULL DEFAULT '0',
  `billsec` int(11) NOT NULL DEFAULT '0',
  `disposition` varchar(45) NOT NULL DEFAULT '',
  `amaflags` int(11) NOT NULL DEFAULT '0',
  `accountcode` varchar(20) NOT NULL DEFAULT '',
  `uniqueid` varchar(32) NOT NULL DEFAULT '',
  `userfield` varchar(255) NOT NULL DEFAULT '',
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `inoutstatus` tinyint(4) NOT NULL DEFAULT '0',
  `recordfile` varchar(80) DEFAULT NULL,
  `dnid` varchar(80) DEFAULT NULL,
  `dialstatus` varchar(20) NOT NULL DEFAULT '0',
  `causecode` tinyint(4) NOT NULL DEFAULT '0',
  `import` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `calldate_index` (`calldate`),
  KEY `inoutstatus_index` (`inoutstatus`,`disposition`)
) ENGINE=MyISAM AUTO_INCREMENT=4755 DEFAULT CHARSET=latin1

